# Generated by Django 5.0.6 on 2024-07-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_inicio', '0002_alter_depoimento_email_alter_depoimento_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='depoimento',
            name='sobrenome',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
