# Generated by Django 5.0.6 on 2024-06-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0006_userprofile_foto_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='estado',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cidade_nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='estado_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='estado_nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
