# Generated by Django 5.0.6 on 2024-07-31 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0014_remove_userprofile_foto_perfil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sobrenome',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
