# Generated by Django 5.0.6 on 2024-08-28 01:10
# Generated by Django 5.0.6 on 2024-08-28 01:10

import storages.backends
from django.db import migrations, models

s3_storage = storages.backends.s3boto3.S3Boto3Storage()

class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0017_alter_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, storage=s3_storage, upload_to='profile_pics/'),
        ),
    ]