# Generated by Django 5.0.6 on 2024-05-28 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('estado', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('P', 'Para adoção'), ('A', 'Adotado')], default='P', max_length=1)),
                ('especie', models.CharField(choices=[('Cachorro', 'Cachorro'), ('Gato', 'Gato')], max_length=10)),
                ('sexo', models.CharField(choices=[('Macho', 'Macho'), ('Fêmea', 'Fêmea')], max_length=10)),
                ('tamanho', models.CharField(choices=[('Grande', 'Grande'), ('Médio', 'Médio'), ('Pequeno', 'Pequeno')], max_length=10)),
                ('cuidados', models.JSONField(blank=True, default=list)),
                ('vive_bem_em', models.JSONField(blank=True, default=list)),
                ('temperamento', models.JSONField(blank=True, default=list)),
                ('sociavel_com', models.JSONField(blank=True, default=list)),
                ('foto_principal', models.ImageField(blank=True, null=True, upload_to='pet_images/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pet_images/')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='divulgar.pet')),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='fotos_secundarias',
            field=models.ManyToManyField(blank=True, related_name='secondary_images', to='divulgar.petimage'),
        ),
    ]
