# Generated by Django 5.0.6 on 2024-06-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divulgar', '0002_pet_dono_pet_historia_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='nome',
            field=models.CharField(help_text='Nome do Pet (máximo de 10 caracteres)', max_length=10),
        ),
    ]
