# Generated by Django 5.0.6 on 2024-06-13 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divulgar', '0010_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='usuario',
        ),
    ]
