# Generated by Django 5.0.6 on 2024-06-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divulgar', '0013_remove_userprofile_nome_alter_userprofile_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nome',
            field=models.CharField(default='Nome Padrão', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='estado',
            field=models.CharField(max_length=100),
        ),
    ]
