# Generated by Django 5.0.6 on 2024-06-16 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divulgar', '0016_remove_pet_descricao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
