# Generated by Django 5.0.6 on 2024-06-22 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divulgar', '0019_pet_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='estado',
        ),
    ]
