# Generated by Django 5.0.6 on 2024-06-06 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adotar', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PedidoAdocao',
        ),
    ]
