# Generated by Django 5.0.6 on 2024-06-16 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_userprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
