# Generated by Django 5.0.6 on 2024-06-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0007_remove_userprofile_cidade_remove_userprofile_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cidade_nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='estado_nome',
            field=models.CharField(max_length=100),
        ),
    ]
