# Generated by Django 5.0.6 on 2024-06-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0008_alter_userprofile_cidade_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='confirmation_token',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='confirmation_token_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
