# Generated by Django 5.0.6 on 2024-07-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0010_remove_userprofile_confirmation_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sobrenome',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
