# Generated by Django 5.0.6 on 2024-07-31 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0015_userprofile_foto_perfil_alter_userprofile_sobrenome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sobrenome',
            field=models.CharField(max_length=100),
        ),
    ]
