# Generated by Django 5.0.6 on 2024-06-13 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divulgar', '0003_alter_pet_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='nome',
            new_name='nome_pet',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='dono',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='usuario',
        ),
    ]
