# Generated by Django 5.0.6 on 2024-06-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divulgar', '0012_pet_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='nome',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cidade',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='estado',
            field=models.CharField(max_length=2),
        ),
    ]
