# Generated by Django 5.0.6 on 2024-06-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divulgar', '0014_userprofile_nome_alter_userprofile_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
