# Generated by Django 5.0.6 on 2024-06-16 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divulgar', '0015_alter_userprofile_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='descricao',
        ),
    ]
