# Generated by Django 5.0.6 on 2024-06-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divulgar', '0018_pet_cidade_pet_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
