# Generated by Django 5.0.6 on 2024-06-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divulgar', '0020_remove_pet_cidade_remove_pet_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
