# Generated by Django 5.0.6 on 2024-07-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divulgar', '0021_pet_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('P', 'Para adoção'), ('A', 'Adotado'), ('E', 'Excluído')], default='P', max_length=1),
        ),
    ]
