# Generated by Django 5.0.6 on 2024-08-28 15:28

from django.db import migrations, models
from storages.backends import s3boto3

s3_storage = s3boto3.S3Boto3Storage()

class Migration(migrations.Migration):

    dependencies = [
        ('divulgar', '0024_pet_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='foto_principal',
            field=models.ImageField(blank=True, null=True, storage=s3_storage, upload_to='pet_images/'),
        ),
    ]