# Generated by Django 5.0.6 on 2024-08-28 01:10

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divulgar', '0024_pet_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='foto_principal',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='pet_images/'),
        ),
    ]
